#!/bin/bash

#this config file for set-up ssh and docker

echo "Begin, you have to be sudo"

sudo apt update -y && apt upgrade -y


sudo apt install openssh-server -y

echo "Port 22
PermitRootLogin no
PasswordAuthentication no
PubkeyAuthentication yes
" >> sudo /etc/ssh/sshd_config

sudo systemctl restart sshd

echo "now with ufw"

sudo apt update
sudo apt install ufw -y

sudo ufw status

sudo ufw allow ssh

sudo ufw allow 22/tcp

sudo ufw enable

sudo ufw status verbose

