#!/bin/bash

echo "Start removing Docker"


sudo systemctl stop docker

sudo systemctl disable docker

sudo apt purge docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin docker-ce-rootless-extras pt-transport-https ca-certificates software-properties-common

sudo apt autoremove -y --purge

sudo rm -f /etc/apt/sources.list.d/docker.list


sudo rm -f /usr/share/keyrings/docker-archive-keyring.gpg

# Remove unused dependencies

sudo rm -rf /var/lib/containerd
# Remove Docker repository file

sudo apt update
# Remove Docker GPG key

# Remove Docker data (WARNING: deletes all containers, images, volumes)
sudo rm -rf /var/lib/docker

# Update package list

echo "Docker has been completely removed"
